"""
generator.py — SQL transformation generator.

Upgrades over v1:
  - Input validation on all parameters
  - Type annotations throughout
  - Clearer confidence threshold handling
  - risk_score capped and documented
"""

from __future__ import annotations

import logging
from typing import Optional

from jinja2 import Template

log = logging.getLogger(__name__)

SQL_TEMPLATE = """
-- Auto-generated by SemZero Autonomous Engine
-- Target Table: {{ target_table }}
-- Dependency Risk Score: {{ risk_score }}

SELECT
    {% for col in mappings %}
    {{ col.source_expr }} AS {{ col.target_col }}{% if not loop.last %},{% endif %}

    {% endfor %}
FROM {{ source_table }}
{% if filters %}
WHERE {{ filters }}
{% endif %};
"""

# Below this confidence level, wrap in COALESCE as a safety guard
_CONFIDENCE_THRESHOLD = 0.8


class SQLGenerator:
    """
    Generates SQL SELECT transformations from source to target schema.
    Injects COALESCE guards for low-confidence column mappings.
    """

    def __init__(self) -> None:
        self.template = Template(SQL_TEMPLATE)

    def generate(
        self,
        mappings: list[dict],
        source_table: str,
        target_table: str,
        risk_report: Optional[list] = None,
        filters: str = "",
    ) -> str:
        """
        Generate a SQL SELECT statement.

        Args:
            mappings:     List of dicts with keys:
                            source_col (str)     — source column name
                            target_col (str)     — target column name
                            confidence (float)   — mapping confidence 0–1
            source_table: Source table name.
            target_table: Target table name.
            risk_report:  Optional list of risk items from BlastRadiusReport.
            filters:      Optional WHERE clause string.

        Returns:
            Generated SQL string.
        """
        if not mappings:
            raise ValueError("mappings list must not be empty.")
        if not source_table or not target_table:
            raise ValueError("source_table and target_table must not be empty.")

        processed: list[dict] = []
        for m in mappings:
            source_col = m.get("source_col", "")
            target_col = m.get("target_col", "")
            confidence = float(m.get("confidence", 1.0))

            if not source_col or not target_col:
                log.warning(f"Skipping mapping with missing source or target: {m}")
                continue

            if confidence < _CONFIDENCE_THRESHOLD:
                expr = f"COALESCE({source_col}, 'MISSING_MAPPING_CHECK_GNN')"
                log.info(
                    f"Low confidence ({confidence:.0%}) on '{source_col}' — wrapping in COALESCE."
                )
            else:
                expr = source_col

            processed.append({"source_expr": expr, "target_col": target_col})

        risk_score = min(len(risk_report), 100) if risk_report else 0

        sql = self.template.render(
            mappings=processed,
            source_table=source_table,
            target_table=target_table,
            risk_score=risk_score,
            filters=filters,
        )

        log.info(
            f"Generated SQL: {source_table} → {target_table}, "
            f"{len(processed)} columns, risk_score={risk_score}"
        )
        return sql
