"""
github_pr.py — SemZero Auto-Repair Pull Request Bot.

Takes a repair plan + drift report and automatically:
  1. Creates a branch: semzero/autofix/<drift-id>
  2. Commits migration.sql and dbt patches
  3. Opens a PR with full context, blast radius, confidence scores
  4. Sets Draft mode for HIGH/CRITICAL severity changes
  5. Adds labels and requested reviewers

Security:
  - Token is never logged or stored
  - Only read from environment variable SEMZERO_GITHUB_TOKEN
  - All identifiers validated before use

Usage:
  from semzero.integrations.github_pr import PRBot
  bot = PRBot(repo="your-org/your-repo")
  bot.open_pr(drift_report, repair_plan, migration_sql)
"""

from __future__ import annotations

import hashlib
import logging
import os
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import requests

log = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

GITHUB_API = "https://api.github.com"
AUTO_MAP_MIN = 0.80  # Only auto-executable PRs above this confidence
DRAFT_SEVERITIES = {"CRITICAL", "HIGH"}  # These always open as Draft PRs

# Labels that must exist in the repo (bot will create them if missing)
LABELS = {
    "semzero/auto": ("0075ca", "SemZero auto-executable repair"),
    "semzero/needs-review": ("e4e669", "SemZero repair needs human review"),
    "semzero/high-risk": ("d93f0b", "SemZero HIGH or CRITICAL severity change"),
    "semzero/drift": ("6e40c9", "Schema drift detected by SemZero"),
}


# ── Data classes ──────────────────────────────────────────────────────────────


@dataclass
class PRResult:
    success: bool
    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    branch: Optional[str] = None
    is_draft: bool = False
    error: Optional[str] = None

    def __str__(self) -> str:
        if self.success:
            tag = "[DRAFT] " if self.is_draft else ""
            return f"✓ {tag}PR #{self.pr_number} opened: {self.pr_url}"
        return f"✗ PR failed: {self.error}"


# ── PR Body template ──────────────────────────────────────────────────────────


def _build_pr_body(
    drift_report: dict,
    repair_plan: dict,
    blast_report: Optional[dict] = None,
    report_url: Optional[str] = None,
) -> str:
    summary = drift_report.get("summary", {})
    events = drift_report.get("events", [])
    actions = repair_plan.get("actions", [])
    detected = drift_report.get("detected_at", "N/A")
    total = summary.get("total_changes", 0)
    by_sev = summary.get("by_severity", {})

    # Severity badge line
    sev_parts = []
    for sev, emoji in [("CRITICAL", "🔴"), ("HIGH", "🟠"), ("MEDIUM", "🟡"), ("LOW", "🟢")]:
        count = by_sev.get(sev, 0)
        if count:
            sev_parts.append(f"{emoji} {count} {sev}")
    sev_line = " &nbsp;·&nbsp; ".join(sev_parts)

    # Events table
    events_rows = "\n".join(
        f"| `{e['node_id']}` | `{e['change_type']}` | {e['severity']} | {e['detail']} |"
        for e in events
    )

    # Actions table
    actions_rows = "\n".join(
        f"| `{a['node_id']}` | `{a['strategy']}` | {a['severity']} | "
        f"{'✅ Auto' if not a['approval_required'] else '⚠️ Review'} | "
        f"{a.get('notes', '')[:80]} |"
        for a in actions
    )

    # Blast radius section
    blast_section = ""
    if blast_report:
        bs = blast_report.get("summary", {})
        blast_section = f"""
## 💥 Blast Radius
| Metric | Value |
|--------|-------|
| Total impacted nodes | {bs.get("total_impacted", 0)} |
| Critical | {bs.get("critical", 0)} |
| High | {bs.get("high", 0)} |
| Max dependency depth | {bs.get("max_depth", 0)} hops |
"""

    # Report link
    report_section = ""
    if report_url:
        report_section = f"\n## 📊 Full Report\n[View SemZero Report]({report_url})\n"

    return f"""# 🤖 SemZero Auto-Repair

> Detected **{total} schema change{"s" if total != 1 else ""}** on `{detected[:19]}` UTC  
> {sev_line}

---

## 📋 Detected Changes

| Node | Change Type | Severity | Detail |
|------|------------|----------|--------|
{events_rows}

---

## 🔧 Repair Actions

| Node | Strategy | Severity | Mode | Notes |
|------|----------|----------|------|-------|
{actions_rows}

---
{blast_section}
{report_section}
## ✅ Validation

- Repair plan generated by SemZero drift engine
- All `AUTO` actions have confidence ≥ {AUTO_MAP_MIN:.0%}
- `APPROVAL_REQUIRED` actions are marked as Draft — do not merge without review

## 🛡️ Safety

- `CRITICAL` and `HIGH` changes are opened as **Draft PRs** — explicit approval required
- Migration SQL is in `semzero/migration.sql`
- To pause auto-repair: comment `@semzero-bot pause`
- To revert: comment `@semzero-bot revert`

---
*Generated by [SemZero](https://github.com/semzero) — Autonomous Schema Intelligence*
"""


# ── Main PR Bot ───────────────────────────────────────────────────────────────


class PRBot:
    """
    Opens GitHub pull requests with SemZero auto-repair patches.

    Args:
        repo:       GitHub repo in "owner/repo" format
        base:       Base branch to PR into (default: main)
        token:      GitHub token. If None, reads SEMZERO_GITHUB_TOKEN env var.
        reviewers:  List of GitHub usernames to request review from
    """

    def __init__(
        self,
        repo: str,
        base: str = "main",
        token: Optional[str] = None,
        reviewers: Optional[list[str]] = None,
    ):
        self.repo = repo
        self.base = base
        self.reviewers = reviewers or []
        self._token = token or os.environ.get("SEMZERO_GITHUB_TOKEN")

        if not self._token:
            raise ValueError(
                "GitHub token not found. Set the SEMZERO_GITHUB_TOKEN "
                "environment variable or pass token= explicitly."
            )

        self._headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    # ── Public API ────────────────────────────────────────────────────────────

    def open_pr(
        self,
        drift_report: dict,
        repair_plan: dict,
        migration_sql: str,
        blast_report: Optional[dict] = None,
        report_url: Optional[str] = None,
        local_repo_path: str = ".",
    ) -> PRResult:
        """
        Full flow: branch → commit → PR.

        Args:
            drift_report:     Output of SchemaDriftDetector.diff().to_dict()
            repair_plan:      Output of RepairEngine.build_plan().to_dict()
            migration_sql:    Output of RepairPlan.render_sql_script()
            blast_report:     Optional blast radius report dict
            report_url:       Optional URL to hosted HTML report
            local_repo_path:  Path to local git repo (for reading current files)
        """
        # Generate a stable drift ID from the report content
        drift_id = self._drift_id(drift_report)
        branch = f"semzero/autofix/{drift_id}"

        # Determine if this should be a draft PR
        by_sev = drift_report.get("summary", {}).get("by_severity", {})
        is_draft = any(by_sev.get(s, 0) > 0 for s in DRAFT_SEVERITIES)

        log.info(f"Opening PR for drift {drift_id} on branch {branch}")

        try:
            # 1. Ensure labels exist
            self._ensure_labels()

            # 2. Get base branch SHA
            base_sha = self._get_branch_sha(self.base)
            if not base_sha:
                return PRResult(success=False, error=f"Base branch '{self.base}' not found.")

            # 3. Create the new branch
            branch_created = self._create_branch(branch, base_sha)
            if not branch_created:
                return PRResult(success=False, error=f"Failed to create branch '{branch}'.")

            # 4. Commit files to the branch
            files = self._build_file_tree(repair_plan, migration_sql)
            commit_msg = self._commit_message(drift_report)
            committed = self._commit_files(branch, base_sha, files, commit_msg)
            if not committed:
                return PRResult(success=False, error="Failed to commit files.")

            # 5. Build PR body
            body = _build_pr_body(drift_report, repair_plan, blast_report, report_url)
            title = self._pr_title(drift_report)
            labels = self._pr_labels(drift_report)

            # 6. Open the PR
            pr_data = self._create_pr(branch, title, body, is_draft)
            if not pr_data:
                return PRResult(success=False, error="Failed to open PR.")

            pr_number = pr_data["number"]
            pr_url = pr_data["html_url"]

            # 7. Add labels
            self._add_labels(pr_number, labels)

            # 8. Request reviewers
            if self.reviewers:
                self._request_reviewers(pr_number, self.reviewers)

            log.info(f"PR #{pr_number} opened: {pr_url}")
            return PRResult(
                success=True,
                pr_url=pr_url,
                pr_number=pr_number,
                branch=branch,
                is_draft=is_draft,
            )

        except Exception as e:
            log.error(f"PR bot failed: {e}")
            return PRResult(success=False, error=str(e))

    # ── GitHub API helpers ────────────────────────────────────────────────────

    def _get(self, path: str, **kwargs) -> Optional[dict]:
        url = f"{GITHUB_API}/{path}"
        for attempt in range(3):
            r = requests.get(url, headers=self._headers, **kwargs)
            if r.status_code == 200:
                return r.json()
            if r.status_code == 403:
                self._handle_rate_limit(r)
            else:
                log.warning(f"GET {path} → {r.status_code}: {r.text[:200]}")
                return None
        return None

    def _post(self, path: str, payload: dict) -> Optional[dict]:
        url = f"{GITHUB_API}/{path}"
        for attempt in range(3):
            r = requests.post(url, headers=self._headers, json=payload)
            if r.status_code in (200, 201):
                return r.json()
            if r.status_code == 403:
                self._handle_rate_limit(r)
            elif r.status_code == 422:
                # Unprocessable — usually means branch/PR already exists
                log.warning(f"POST {path} 422: {r.json().get('message', '')}")
                return r.json()
            else:
                log.warning(f"POST {path} → {r.status_code}: {r.text[:200]}")
                return None
        return None

    def _handle_rate_limit(self, response: requests.Response) -> None:
        reset = int(response.headers.get("X-RateLimit-Reset", time.time() + 60))
        wait = max(reset - int(time.time()), 1)
        log.warning(f"GitHub rate limit hit. Waiting {wait}s...")
        time.sleep(wait)

    def _get_branch_sha(self, branch: str) -> Optional[str]:
        data = self._get(f"repos/{self.repo}/git/ref/heads/{branch}")
        return data["object"]["sha"] if data else None

    def _create_branch(self, branch: str, sha: str) -> bool:
        data = self._post(
            f"repos/{self.repo}/git/refs",
            {
                "ref": f"refs/heads/{branch}",
                "sha": sha,
            },
        )
        if data and data.get("ref"):
            return True
        # Branch may already exist — that's OK
        if data and "already exists" in data.get("message", ""):
            log.info(f"Branch {branch} already exists, reusing.")
            return True
        return False

    def _build_file_tree(self, repair_plan: dict, migration_sql: str) -> dict[str, str]:
        """Returns a dict of {filepath: content} to commit."""
        files: dict[str, str] = {}

        # Main migration SQL
        files["semzero/migration.sql"] = migration_sql

        # dbt patches (one file per action that has a dbt_patch)
        for action in repair_plan.get("actions", []):
            if action.get("dbt_patch"):
                node_id = action["node_id"].replace(".", "_").replace("/", "_")
                filepath = f"semzero/dbt_patches/{node_id}.yml"
                files[filepath] = action["dbt_patch"]

        # Summary JSON
        import json

        files["semzero/repair_summary.json"] = json.dumps(repair_plan, indent=2)

        return files

    def _commit_files(
        self,
        branch: str,
        base_sha: str,
        files: dict[str, str],
        message: str,
    ) -> bool:
        """Creates a single commit with all files using the Git Trees API."""
        import base64

        # Create blobs for each file
        tree_items = []
        for filepath, content in files.items():
            blob = self._post(
                f"repos/{self.repo}/git/blobs",
                {
                    "content": content,
                    "encoding": "utf-8",
                },
            )
            if not blob:
                log.error(f"Failed to create blob for {filepath}")
                return False
            tree_items.append(
                {
                    "path": filepath,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob["sha"],
                }
            )

        # Get current tree SHA
        commit_data = self._get(f"repos/{self.repo}/git/commits/{base_sha}")
        if not commit_data:
            return False
        tree_sha = commit_data["tree"]["sha"]

        # Create new tree
        new_tree = self._post(
            f"repos/{self.repo}/git/trees",
            {
                "base_tree": tree_sha,
                "tree": tree_items,
            },
        )
        if not new_tree:
            return False

        # Create commit
        new_commit = self._post(
            f"repos/{self.repo}/git/commits",
            {
                "message": message,
                "tree": new_tree["sha"],
                "parents": [base_sha],
            },
        )
        if not new_commit:
            return False

        # Update branch ref
        update = self._post(
            f"repos/{self.repo}/git/refs/heads/{branch}",
            {
                "sha": new_commit["sha"],
                "force": False,
            },
        )
        # Note: updating refs uses PATCH not POST — handle separately
        url = f"{GITHUB_API}/repos/{self.repo}/git/refs/heads/{branch}"
        r = requests.patch(
            url,
            headers=self._headers,
            json={
                "sha": new_commit["sha"],
                "force": False,
            },
        )
        return r.status_code in (200, 201)

    def _create_pr(
        self,
        head: str,
        title: str,
        body: str,
        draft: bool,
    ) -> Optional[dict]:
        return self._post(
            f"repos/{self.repo}/pulls",
            {
                "title": title,
                "body": body,
                "head": head,
                "base": self.base,
                "draft": draft,
            },
        )

    def _add_labels(self, pr_number: int, labels: list[str]) -> None:
        self._post(
            f"repos/{self.repo}/issues/{pr_number}/labels",
            {
                "labels": labels,
            },
        )

    def _request_reviewers(self, pr_number: int, reviewers: list[str]) -> None:
        self._post(
            f"repos/{self.repo}/pulls/{pr_number}/requested_reviewers",
            {
                "reviewers": reviewers,
            },
        )

    def _ensure_labels(self) -> None:
        """Create SemZero labels in the repo if they don't exist."""
        existing = self._get(f"repos/{self.repo}/labels") or []
        existing_names = {l["name"] for l in existing}

        for name, (colour, description) in LABELS.items():
            if name not in existing_names:
                self._post(
                    f"repos/{self.repo}/labels",
                    {
                        "name": name,
                        "color": colour,
                        "description": description,
                    },
                )

    # ── Naming helpers ────────────────────────────────────────────────────────

    def _drift_id(self, drift_report: dict) -> str:
        """Stable 8-char ID from drift report content."""
        raw = drift_report.get("detected_at", "") + str(drift_report.get("summary", {}))
        return hashlib.sha256(raw.encode()).hexdigest()[:8]

    def _commit_message(self, drift_report: dict) -> str:
        events = drift_report.get("events", [])
        by_sev = drift_report.get("summary", {}).get("by_severity", {})
        total = drift_report.get("summary", {}).get("total_changes", 0)

        # Lead with the most severe change
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            for e in events:
                if e["severity"] == sev:
                    ct = e["change_type"]
                    table = e["node_id"].split(".")[0]
                    return (
                        f"semzero: autofix {ct} on {table} "
                        f"({total} change{'s' if total != 1 else ''} total)"
                    )
        return "semzero: autofix schema drift"

    def _pr_title(self, drift_report: dict) -> str:
        events = drift_report.get("events", [])
        by_sev = drift_report.get("summary", {}).get("by_severity", {})
        total = drift_report.get("summary", {}).get("total_changes", 0)

        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            for e in events:
                if e["severity"] == sev:
                    ct = e["change_type"]
                    node = e["node_id"]
                    return f"[SemZero] Auto-repair: {ct} on `{node}` (+{total - 1} more)"

        return f"[SemZero] Auto-repair: {total} schema changes detected"

    def _pr_labels(self, drift_report: dict) -> list[str]:
        by_sev = drift_report.get("summary", {}).get("by_severity", {})
        labels = ["semzero/drift"]

        has_high_risk = any(by_sev.get(s, 0) > 0 for s in DRAFT_SEVERITIES)
        if has_high_risk:
            labels.append("semzero/high-risk")
            labels.append("semzero/needs-review")
        else:
            labels.append("semzero/auto")

        return labels
